  /*
 Created on : 06-Abr-2018
 Author     : Ismael Martin Ramirez [imartinr01@informatica.iesvalledeljerteplasencia.es]
 */
console.log("JS Rautins iniciado.")

<!--Configuracion de ngRoute -> Rautins-->
         app.config(['$routeProvider',
            function($routeProvider){             
                $routeProvider.           
            when('/ciudad',{
             templateUrl:'ciudad/plasencia/inicio/inicio.html',
           }).
           when('/gobierno',{
             templateUrl:'ciudad/plasencia/ayuntamiento/gobierno.html',
           }).
           when('/barrios',{
             templateUrl:'ciudad/plasencia/barrio/barrio.html',
           }).
            when('/sobre/OpenDataPlasencia',{
             templateUrl:'ciudad/plasencia/sobre/sobre.html',
           }).
           when('/organismosSociales',{
             templateUrl:'ciudad/plasencia/organismo/organismo.html',
           }).
            when('/gobierno/xml',{
             templateUrl:'ciudad/plasencia/ayuntamiento/export/xml.html',
           }).
            when('/gobierno/json',{
             templateUrl:'ciudad/plasencia/ayuntamiento/export/json.html',
           }).
            when('/gobierno/csv',{
             templateUrl:'ciudad/plasencia/ayuntamiento/export/csv.html',
           }).
            when('/gobierno/html',{
             templateUrl:'ciudad/plasencia/ayuntamiento/export/html.html',
           }).
             when('/barrios/html',{
             templateUrl:'ciudad/plasencia/barrio/export/html.html',
           }).
            when('/barrios/xml',{
             templateUrl:'ciudad/plasencia/barrio/export/xml.html',
           }).
            when('/barrios/json',{
             templateUrl:'ciudad/plasencia/barrio/export/json.html',
           }).
            when('/barrios/csv',{
             templateUrl:'ciudad/plasencia/barrio/export/csv.html',
           }).
            when('/organismosSociales/xml',{
             templateUrl:'ciudad/plasencia/organismo/export/xml.html',
           }).
            when('/organismosSociales/json',{
             templateUrl:'ciudad/plasencia/organismo/export/json.html',
           }).
            when('/organismosSociales/csv',{
             templateUrl:'ciudad/plasencia/organismo/export/csv.html',
           }).
            when('/organismosSociales/html',{
             templateUrl:'ciudad/plasencia/organismo/export/html.html',
           }).
            when('/ciudadDePlasencia/xml',{
             templateUrl:'ciudad/plasencia/inicio/export/xml.html',
           }).
            when('/ciudadDePlasencia/json',{
             templateUrl:'ciudad/plasencia/inicio/export/json.html',
           }).
            when('/ciudadDePlasencia/csv',{
             templateUrl:'ciudad/plasencia/inicio/export/csv.html',
           }).
            when('/ciudadDePlasencia/html',{
             templateUrl:'ciudad/plasencia/inicio/export/html.html',
           }).
            otherwise({
             redirectTo:'/',
             templateUrl:'ciudad/plasencia/inicio/inicio.html',
           })
             
         }])